#!/usr/bin/env python
import os
import readline
import rlcompleter
import atexit

from see import see
from show import show


readline.parse_and_bind('tab:complete')

# Django Helpers
def SECRET_KEY(size=50):
    "Generates a new SECRET_KEY that can be used in a project settings file."
    from random import choice
    return ''.join([
        choice('abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)') for i in range(size)])
