#!/bin/bash

BASE_DIR=/usr/share/backgrounds/xolotl

IMAGE_PATH="$(find $BASE_DIR -type f | shuf -n 1)"

# convert -scale 2560x1440 source-image.jpg lockscreen.png

i3lock \
  -i $IMAGE_PATH \
  --datepos="tx+24:ty+25" \
  --clock --datestr "Type password to unlock..." \
  --insidecolor=00000000 --ringcolor=ffffffff --line-uses-inside \
  --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
  --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
  --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+290:h-120" \
  --radius=20 --ring-width=3 --veriftext="" --wrongtext="" \
  --timecolor="ffffffff" --datecolor="ffffffff"
