[theme]
name = "solarized-dark"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 21

[[block]]
block = "custom"
command = "hostname"
interval = 10000

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "net"
device = "wlp61s0"
ssid = true
interval = 5
speed_down = false
speed_up = false

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {power}W"

[[block]]
block = "time"
interval = 60
format = "%F %R"