(require 'color-theme)
(color-theme-initialize)
;(color-theme-calm-forest)
(color-theme-ld-dark)
(ansi-color-for-comint-mode-on)
(setq inhibit-startup-message t)
(set-default 'indicate-empty-lines nil)
