(defun fixfile ()
  "Fix the suppresion list"
  (interactive)
  (set-buffer-file-coding-system 'utf-8-unix t)
  (while (re-search-forward "^...$" nil t)
    (replace-match ""))
  (goto-line 1)
  (while (re-search-forward "^..$" nil t)
    (replace-match ""))
  (goto-line 1)
  (while (re-search-forward "^.$" nil t)
    (replace-match ""))
  (goto-line 1)
  (flush-lines "^$")
  )
