; Theme generated through http://alexpogosyan.com/color-theme-creator/
(defun my-very-own ()
  (interactive)
  (color-theme-install
   '(my-very-own
      ((background-color . "#171717")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#114b3c"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#72963c"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:foreground "#3167a0"))))
     (font-lock-string-face ((t (:foreground "#e75fd8"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'my-very-own)
(require 'color-theme)
(color-theme-initialize)
;(color-theme-calm-forest)
;(color-theme-ld-dark)
(my-very-own)
(ansi-color-for-comint-mode-on)
(setq inhibit-startup-message t)
(set-default 'indicate-empty-lines nil)
(require 'cursor-chg)
(blink-cursor-mode -1)      ;; No blinking please
(change-cursor-mode 1)
(change-cursor-mode 1) ; On for overwrite/read-only/input mode
(toggle-cursor-type-when-idle 1) ; On when idle
