; Theme generated through http://alexpogosyan.com/color-theme-creator/
(defun my-very-own ()
  (interactive)
  (color-theme-install
   '(my-very-own
      ((background-color . "#171717")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#114b3c"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#72963c"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:foreground "#3167a0"))))
     (font-lock-string-face ((t (:foreground "#e75fd8"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'my-very-own)

(defun sun-light ()
  (interactive)
  (color-theme-install
   '(sun-light
      ((background-color . "#101e2e")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (region ((t (:background "#455f26"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#ebe333"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:foreground "#37c5d2"))))
     (font-lock-string-face ((t (:foreground "#e359d4"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'sun-light)


(defun robs-colours ()
  (interactive)
  (color-theme-install
   '(your-config-name-here
      ((background-color . "#343232")
      (background-mode . light)
      (border-color . "#000000")
      (cursor-color . "#333333")
      (foreground-color . "#fcf6d4")
      (mouse-color . "black"))
     (fringe ((t (:background "#000000"))))
     (mode-line ((t (:foreground "#000000" :background "#666666"))))
     (region ((t (:background "#999999"))))
     (font-lock-builtin-face ((t (:foreground "#b5dc5b"))))
     (font-lock-comment-face ((t (:foreground "#6b6a61"))))
     (font-lock-function-name-face ((t (:foreground "#df7cb7"))))
     (font-lock-keyword-face ((t (:foreground "#dfa09b"))))
     (font-lock-string-face ((t (:foreground "#c9a42c"))))
     (font-lock-type-face ((t (:foreground"#74c887"))))
     (font-lock-variable-name-face ((t (:foreground "#f3d216"))))
     (minibuffer-prompt ((t (:foreground "#7299ff" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))
(provide 'robs-colours)


(require 'color-theme)
(color-theme-initialize)
;(color-theme-calm-forest)
;(color-theme-ld-dark)
(sun-light)
;(robs-colours)
(ansi-color-for-comint-mode-on)
(setq inhibit-startup-message t)
(set-default 'indicate-empty-lines nil)
(require 'cursor-chg)
(blink-cursor-mode -1)      ;; No blinking please
(change-cursor-mode 1)
(change-cursor-mode 1) ; On for overwrite/read-only/input mode
(toggle-cursor-type-when-idle 1) ; On when idle
